name: user_repository
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  equatable: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
